module.exports = {
  ap: {
    name: "AndraPradesh",
    frequency: "Yearly",
    monthOfDeduction: "December",
    dueDate: "31st Jan",
    employeeContribution: "30",
    employerContribution: "70",
    updatedOn: "02 July 2021",
    rules: [
      "Any Establishment/Employer employing 1 or more persons",
      "All employees except employees working in part-time position,apprentice and managerial position",
    ],
    Link: "http://labour.ap.gov.in/ELabour/Views/RecentAmendementNewActs.aspx",
  },
  ch: {
    name: "Chandigarh",
    frequency: "Monthly",
    monthOfDeduction: "June, December",
    dueDate: "15 July and 15 January",
    employeeContribution: "15",
    employerContribution: "45",
    updatedOn: "02 July 2021",
    rules: [
      "Any Establishment/Employer employing 1 or more persons",
      "All employees except in managerial/administrative/supervisory capacity drawing wages more than ₹ 10,000 per month",
    ],
    Link: "http://cglabour.nic.in/ShramKalyanMandal/abhidayrashi.aspx",
  },
  dl: {
    name: "Delhi",
    frequency: "Half Yearly",
    monthOfDeduction: "June, December",
    dueDate: "15 July and 15 January",
    employeeContribution: "0.75",
    employerContribution: "2.25",
    updatedOn: "02 July 2021",
    rules: [
      "Any Establishment employing 5 or more persons",
      "All employees except in managerial/administrative/supervisory capacity drawing wages more than ₹ 2,500 per month",
    ],
    Link: "http://www.delhi.gov.in/wps/wcm/connect/DOIT_Labour/labour/notification/labour+welfare+funds",
  },
  goa: {
    name: "Goa",
    frequency: "Half Yearly",
    monthOfDeduction: "June, December",
    dueDate: "15 July and 15 January",
    employeeContribution: "60",
    employeeContribution: "180",
    updatedOn: "02 July 2021",
    rules: [
      "Any Establishment/Employer employing 1 or more persons",
      "All employees except in managerial/administrative/supervisory capacity drawing wages more than ₹ 1,600 per month",
    ],
    Link: "http://labour.goa.gov.in/index.php/goa-lwb/",
  },

  gj: {
    name: "Gujrat",
    frequency: "Half Yearly",
    monthOfDeduction: "June, December",
    dueDate: "15 July and 15 January",
    employeeContribution: "6",
    employerContribution: "12",
    updatedOn: "02 July 2021",
    rules: [
      "Any Establishment/Employer employing 10 or more persons",
      "All employees except in managerial/supervisory capacity drawing wages more than ₹ 3,500 per month",
    ],
    Link: "https://glwb.gujarat.gov.in/",
  },
  hr: {
    name: "Haryana",
    frequency: "Monthly",
    monthOfDeduction: "Every Month",
    dueDate: "Last day of every month",
    employeeContribution: "25",
    employerContribution: "50",
    updatedOn: "02 July 2021",
    rules: [
      "Any Establishment/Employer employing 10 or more persons",
      "All employees employed,directly by or through any agency,including a contractor for remuneration in any Factory/Est",
    ],
    Link: "https://hrylabour.gov.in/content/cms/MTU",
  },
  kr: {
    name: "Karnataka",
    frequency: "Yearly",
    monthOfDeduction: "December",
    dueDate: "15th Jan",
    employeeContribution: "20",
    employerContribution: "40",
    updatedOn: "02 July 2021",
    rules: [
      "Any Establishment/Employer employing 50 or more persons",
      "All employees who are employed for wages to do any work skilled/unskilled/manual/clerical,in an establishment",
    ],
    Link: "http://labour.kar.nic.in/labour/klwboard.htm",
  },
  ker: {
    name: "Kerala",
    frequency: "Half Yearly",
    monthOfDeduction: "June, December",
    dueDate: "15 July and 15 January",
    employeeContribution: "45",
    employerContribution: "45",
    updatedOn: "22 June 2022",
    rules: [
      "Any Establishment/Employer employing 1 or more persons",
      "All employees under the purview of the Kerala Labour Welfare Fund Act, 1975. For Shops & Establishments under the purview of The Kerala Shops And Commercial Establishments Workers Welfare Fund Act,2006,Employee and Employer has to contribute ₹ 20 each, every month by 30 th and due date is 5 th of every month.",
    ],
    Link: "http://peedika.kerala.gov.in/",
  },
  mp: {
    name: "MadhyaPradesh",
    frequency: "Half Yearly",
    monthOfDeduction: "June, December",
    dueDate: "15 July and 15 January",
    employeeContribution: "10",
    employerContribution: "30",
    updatedOn: "02 July 2021",
    rules: [
      "Any Establishment/Employer employing 1 or more persons",
      "All employees except employees in managerial/supervisory capacity drawing wages more than ₹ 10,000 per month",
    ],
    Link: "http://shramsewa.mp.gov.in/labourwelfareboard/en-us/",
  },
  mh: {
    name: "Maharashtra",
    frequency: "Half Yearly",
    monthOfDeduction: "June, December",
    dueDate: "15 July and 15 January",
    employeeContribution: "6/12",
    employerContribution: "12/36",
    updatedOn: "02 July 2021",
    rules: [
      "Any Establishment/Employer employing 5 or more persons",
      "All employees except in managerial/supervisory capacity. Contributions vary based on wage upto ₹ 3,000 and above ₹ 3,000 per month",
    ],
    Link: "https://mahakamgar.maharashtra.gov.in/index.htm",
  },
  od: {
    name: "Orissa",
    frequency: "Half Yearly",
    monthOfDeduction: "June, December",
    dueDate: "15 July and 15 January",
    employeeContribution: "10",
    employerContribution: "20",
    updatedOn: "02 July 2021",
    rules: [
      "Any Establishment/Employer employing 20 or more persons",
      "All employees except employees working in part-time position,apprentice and managerial position",
    ],
    Link: "http://www.labdirodisha.gov.in",
  },
  pun: {
    name: "Punjab",
    frequency: "Monthly",
    monthOfDeduction: "Every Month",
    dueDate: "15 April and 15 October",
    employeeContribution: "5",
    employerContribution: "20",
    updatedOn: "02 July 2021",
    rules: [
      "Any Establishment/Employer employing 20 or more persons",
      "All employees employed for hire/reward to do any work,skilled/unskilled,manual/clerical,in an establishment",
    ],
    Link: "http://pblabour.gov.in/",
  },
  tn: {
    name: "TamilNadu",
    frequency: "Yearly",
    monthOfDeduction: "December",
    dueDate: "31st Jan",
    employeeContribution: "50",
    employerContribution: "100",
    updatedOn: "01 Oct 2021",
    rules: [
      "Any Establishment/Employer employing 5 or more persons",
      "All employees except those in part-time,apprentice,managerial positions drawing wages more than ₹ 15,000 per month",
    ],
    Link: "https://www.lwb.tn.gov.in/",
  },
  tel: {
    name: "Telangana",
    frequency: "Yearly",
    monthOfDeduction: "December",
    dueDate: "31st Jan",
    employeeContribution: "2",
    employerContribution: "5",
    updatedOn: "02 July 2021",
    rules: [
      "Any Establishment/Employer employing 20 or more persons",
      "All employees except employees in managerial/supervisory capacity drawing wages more than ₹ 1,600 per month",
    ],
    Link: "https://labour.telangana.gov.in/AboutUs.do",
  },
  wb: {
    name: "WestBengal",
    frequency: "Half Yearly",
    monthOfDeduction: "June, December",
    dueDate: "15 July and 15 January",
    employeeContribution: "3",
    employerContribution: "15",
    dueDate: "02 July 2021",
    rules: [
      "Any Establishment/Employer employing 10 or more persons",
      "All employees except employees in managerial/supervisory capacity drawing wages more than ₹ 1,600 per month",
    ],
    Link: "http://www.wblwb.org/html/index.php",
  },
};
